### ISSUE TITLE
"Other payment methods are coming soon." zmenit na...

### ISSUE THREAD

**Issue by sipak** [ParalelniPolis/pp-tickets#7]
"PayPal + ... payment methods are coming soon."
Napsal bych tam konkretne, ktere payment methods jeste chceme zaradit, at lidi zbytecne necekaji, treba ta jejich oblibena metoda nedorazi, nebo bych to uplne vypustil

**Comment by pavelkraleu** [comment]
Fixed
https://github.com/ParalelniPolis/pp-tickets/commit/01b7f673b716f18ea08db558ba112dd6d6ebb1d6
